// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfofclacldpelpsxrecz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmb2ZjbGFjbGRwZWxwc3hyZWN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NzMzNjUsImV4cCI6MjA2NjQ0OTM2NX0.S5ms9Y4tVk26yaP0yEfFNcS9FWNTmksoZaH98TFUjAQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);